# Checks domain and SSL status, then raises an issue if either is expiring soon
name: 🌎 Check Domain Expiry
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 6' # Every Saturday morning.
jobs:
  check-domain:
    runs-on: ubuntu-latest
    name: Check domain
    strategy:
      matrix:
        domain:
          - https://awesome-privacy.xyz
    steps:
      - name: Check domain SSL and registry expire date
        id: check-domain
        with:
          url: ${{ matrix.domain }}
      - name: Raise issue if domain expiring soon
        if: ${{ steps.check-domain.outputs.paid-till-days-left && steps.check-domain.outputs.paid-till-days-left < 30 }}
        uses: rishabhgupta/git-action-issue@v2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          assignees: Lissy93
          title: '[WEBSITE] Domain Expiring Soon'
          body: >
            **Priority Notice**
            Domain, ${{ matrix.domain }} will expire in ${{ steps.check-domain.outputs.paid-till-days-left }} days.
            @Lissy93 - Please take action immediately to prevent any downtime
      - name: Raise issue if SSL Cert expiring soon
        if: ${{ steps.check-domain.outputs.ssl-expire-days-left && steps.check-domain.outputs.ssl-expire-days-left < 14 }}
        uses: rishabhgupta/git-action-issue@v2
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          assignees: Lissy93
          title: '[WEBSITE] SSL Cert Expiring Soon'
          body: >
            **Priority Notice**
            The SSL Certificate for ${{ matrix.domain }} will expire in ${{ steps.check-domain.outputs.ssl-expire-days-left }} days, on ${{ steps.check-domain.outputs.ssl-expire-date }}.
            @Lissy93 - Please take action immediately to prevent any downtime
